# Generated by Django 3.2.4 on 2021-06-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='companyid',
        ),
        migrations.RemoveField(
            model_name='address',
            name='supplierid',
        ),
        migrations.RemoveField(
            model_name='address',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='productid',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=2550, null=True),
        ),
    ]
