# Generated by Django 3.2.4 on 2021-06-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='authuserid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='authuser',
            field=models.ForeignKey(db_column='AuthUserID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(db_column='ProductID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='detail',
            field=models.CharField(blank=True, db_column='Detail', max_length=2550, null=True),
        ),
    ]
