# Generated by Django 3.2.4 on 2021-06-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210619_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='label',
            field=models.IntegerField(db_column='Label', default=1),
            preserve_default=False,
        ),
    ]
